name: Android App Screenshot Test
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  emulator-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Make Gradle wrapper executable
        run: chmod +x ./android/gradlew
        
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install and start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: |
            # Start Metro bundler in background
            npm start &
            
            # Wait for Metro to start
            sleep 30
            
            # Install app on emulator
            cd android && ./gradlew installDebug
            
            # Launch app
            adb shell monkey -p com.bloomchats -c android.intent.category.LAUNCHER 1
            
            # Wait for app to stabilize
            sleep 20
            
            # Take screenshot
            adb shell screencap -p /sdcard/screen.png
            
            # Pull screenshot from device
            adb pull /sdcard/screen.png
            
            echo "Screenshot captured at ./screen.png"

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: app-screenshot
          path: screen.png
          
      - name: Add screenshot to summary
        run: |
          echo "## App Screenshot" >> $GITHUB_STEP_SUMMARY
          echo "![App Screenshot](./screen.png)" >> $GITHUB_STEP_SUMMARY
